name: Localnomics
favicon: null
layout_spectrum: 0.8062766073271632
typography_spectrum: 0.9081
title: Local Economic Development
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffd300'
    - '#99dae7'
    - '#000000'
    - '#ff6a00'
    - '#bf3700'
  brandStrength: 0.8125
  lightness: 0.125
  saturation: 0.6213809032924473
  rhythmicContrast: 0.75
purpose: []
